let a = 1;
 let b = true;
 let c = "Hola";
 let d = null;
 let e;
 let f = 2n ** 60n;
 let g = new Date();
 let h = [1,2,3,4];
 let i = 'Hola';
 let j = { x: 2.0, y: -3.6 };
 let k = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;

console.log(a, typeof a);
console.log(b, typeof b);
console.log(c, typeof c);
console.log(d, typeof d);   
console.log(e, typeof e);
console.log(f, typeof f);   
console.log(g, typeof g);
console.log(h, typeof h);   
console.log(i, typeof i);
console.log(j, typeof j);   
console.log(k, typeof k);
